name: Update README with Repositories

on:
  push:
    branches:
      - main  # Update with your branch name

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate README
        run: |
          echo "# My GitHub Repositories\n" > README.md
          echo "## Projects\n" >> README.md
          curl -s "https://api.github.com/users/minimalframer/repos?per_page=5" |
            jq -r '.[] | "- [**\(.name)**](\(.html_url)): \(.description)"' >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update README with latest repositories [skip ci]"
          git push
